### ISSUE TITLE
...

### ISSUE THREAD

**Issue by beaconcreaft** [padreon/TittleADR#6]
Kok bro kenapa di public? Padahal saya beli 50k. Cuman jadi terbuang pluginya, karena di publik. Gw ga bisa buka line karna dah di hapus

**Comment by padreon** [comment]
lu yg bocorin plugin ini kok lu protes?
klo ga mau gw public plugin private ga ush di share ke org.
jangan di dijual kembali

**Comment by padreon** [comment]
Klo mau jualan plugin ga ush ngejual plugin bkinan org

**Comment by amlxp** [comment]
> lu yg bocorin plugin ini kok lu protes?
> klo ga mau gw public plugin private ga ush di share ke org.
> jangan di dijual kembali

Ydh gpp. Publik aja

**Comment by amlxp** [comment]
Gw beacon craft

**Comment by amlxp** [comment]
Ganti akun
