### ISSUE TITLE
Lanjutan

### ISSUE THREAD

**Issue by amlxp** [padreon/TittleADR#7]
Tapi Xa ga masuk akal.
Misal dah gw beli motor. Nah motornya dah jdi milik tapi masih tetap pemiliknya yang buat tu motor, saat gw pakai ada yang mau beli nah di jual lagi tapi keterangan dibuatnya masih tercantum.

Sedangkan gw beli plugin. Trus gw jual tapi deskripsinya masih ada terpampang PhpStrom.

Apa yang salah di gw :?

**Comment by padreon** [comment]
Barang itu motor ga bisa di double, sedangkan script bisa di double. Klo itu buatan lu trs ada yg jual seharusnya itu yg jual lu. Gw aja sengaja buat ga dijual lagi biar plugin lu ga ada yg punya eh lu malah kyk anjg ngejual ya gw ga diam gitu aja. Klo lu transaksi yg berbau script atau bahan bisa di double itu pengunaan nya cuma di lu doang dan ga bisa di sebar luaskan atau
