### ISSUE TITLE
Lanjutan #3

### ISSUE THREAD

**Issue by amlxp** [padreon/TittleADR#8]
Contohnya aja Dev lain gw lupa yang jual Top Xp/Money/Mine, Pandu keknya. Dia jual plugin itu cuman yang belinya, jual lagi tapi dia cantum yang pembuatnya itu.

Kalau kyk gini gw yg di rugikan :?

**Comment by padreon** [comment]
Lu yg di rugikan? Gw yg bkin, gw yg lelah, lu cuma beli doang trs lu jual lgi ke bnyak org trs siapa yg dirugikan. Gw sengaja ga di publish di yt gw biar cuma elu yg ada plugin nya.
