### ISSUE TITLE
Lanjutan #4

### ISSUE THREAD

**Issue by amlxp** [padreon/TittleADR#9]
Tapi ada di plugin lu LICENSE? Lu ga bilang pluginnya jngn di jualin lgi. :?

**Comment by padreon** [comment]
Gw pernah bilang kok cek aja di Line lu, dan tiap org yg order ke gw, gw slalu bilang gitu. Kegunaan author di plugin.yml juga gitu, klo mau disebarin atau apa gitu minta ijin jangan sok claim punya lu trs gnti src seenaknya lalu dijual

**Comment by amlxp** [comment]
Ok. Nanya lgi knp Top XP/Farmer/Miner yang beli trus dijual lgi tpi pemilik plugin itu tidak ngapa2? Ada License? Atau sebelumnya yg pembuat plugin itu yg dijual tidak ngomong "tidak boleh dijual lgi" :?

**Comment by padreon** [comment]
Mereka tau ga? Coba lu bilang klo plugin nya dijual org

**Comment by padreon** [comment]
Lucu ajg, klo mau ngejual plugin karya sendiri dong.

**Comment by padreon** [comment]
Jangan kyk babi babi di yt, beli gnti nama trs claim punya dia sendiri

**Comment by amlxp** [comment]
Menurut lu ? Gw udah laris?

**Comment by amlxp** [comment]
Menurut lu gw jual plugin lu brp orng?

**Comment by amlxp** [comment]
Ga sampai 3-10?

**Comment by amlxp** [comment]
Atau 2-20?

**Comment by padreon** [comment]
Emgnya perlu gw harus tau berapa org yg lu jual?
